import {app,BrowserWindow,dialog,ipcMain,Menu,shell,Tray} from "electron";
import updater from "electron-updater";
import {spawn} from "node:child_process";
import {appendFileSync,copyFileSync,cpSync,existsSync,mkdirSync,readFileSync,writeFileSync} from "node:fs";
import {dirname,join,resolve} from "node:path";
import {fileURLToPath} from "node:url";

const projectRoot=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const {autoUpdater}=updater;
const children=[];
let quitting=false;
let mainWindow=null;
let tray=null;
let updateState={status:"idle",version:null,error:null};

function log(message){try{const logDir=join(app.getPath("userData"),"logs");mkdirSync(logDir,{recursive:true});appendFileSync(join(logDir,"desktop.log"),`[${new Date().toISOString()}] ${message}\n`)}catch{/* Logging must never prevent the desktop app from starting. */}}
function childEnvironment(){const dataDir=join(app.getPath("userData"),"data");const bundledMpv=process.platform==="win32"?(app.isPackaged?join(process.resourcesPath,"mpv","mpv.exe"):join(projectRoot,"vendor","mpv","mpv.exe")):"/usr/bin/mpv";const ffmpeg=process.platform==="win32"?join(process.resourcesPath,"ffmpeg","ffmpeg.exe"):"/usr/bin/ffmpeg";return {...process.env,ELECTRON_RUN_AS_NODE:"1",TORR_DATA_DIR:dataDir,TORRSERVER_URL:"http://127.0.0.1:8090",TORR_LOCAL_API_PORT:"3001",REMOTE_POSTERS:"1",MPV_PATH:process.env.MPV_PATH||bundledMpv,...(app.isPackaged?{FFMPEG_PATH:ffmpeg}:{})}}
function runNode(script,args=[]){const child=spawn(process.execPath,[script,...args],{cwd:projectRoot,env:childEnvironment(),windowsHide:true,stdio:"ignore"});children.push(child);child.on("error",error=>log(`child error: ${error.message}`));child.on("exit",code=>log(`${script} exited with ${code}`));return child}
async function online(url,timeout=1200){try{return (await fetch(url,{signal:AbortSignal.timeout(timeout)})).ok}catch{return false}}
async function waitFor(url,timeoutMs=60000){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){if(await online(url,2000))return;await new Promise(resolve=>setTimeout(resolve,400))}throw new Error(`Сервис не ответил: ${url}`)}
function prepareTorrServer(){const targetDir=join(app.getPath("userData"),"torrserver");mkdirSync(targetDir,{recursive:true});const sourceDir=app.isPackaged?join(process.resourcesPath,"torrserver"):join(projectRoot,"bin");for(const name of ["config.db","settings.json","viewed.json","trackers.txt","rutor.ls"]){const source=join(sourceDir,name),target=join(targetDir,name);if(existsSync(source)&&!existsSync(target))copyFileSync(source,target)}const settingsPath=join(targetDir,"settings.json");try{const settings=JSON.parse(readFileSync(settingsPath,"utf8"));if(settings?.BitTorr){settings.BitTorr.EnableRutorSearch=true;writeFileSync(settingsPath,JSON.stringify(settings,null,2))}}catch(error){log(`TorrServer settings migration failed: ${error.message}`)}const name=process.platform==="win32"?"TorrServer-windows-amd64.exe":"TorrServer-linux-amd64";const executable=app.isPackaged?join(sourceDir,name):join(projectRoot,"bin",name);return {executable,targetDir}}
async function startServices(){if(!await online("http://127.0.0.1:8090/echo")){const {executable,targetDir}=prepareTorrServer();if(!existsSync(executable))throw new Error("TorrServer не найден в ресурсах приложения");const torrServer=spawn(executable,[],{cwd:targetDir,windowsHide:true,stdio:"ignore"});children.push(torrServer);torrServer.on("error",error=>log(`TorrServer error: ${error.message}`));await waitFor("http://127.0.0.1:8090/echo",30000)}if(!await online("http://127.0.0.1:3001/api/health"))runNode(join(projectRoot,"server","api.mjs"));if(!await online("http://127.0.0.1:3000/"))runNode(join(projectRoot,"node_modules","vinext","dist","cli.js"),["start"]);await Promise.all([waitFor("http://127.0.0.1:3001/api/health"),waitFor("http://127.0.0.1:3000/")])}
function showWindow(){if(!mainWindow)return;if(mainWindow.isMinimized())mainWindow.restore();mainWindow.show();mainWindow.focus()}
function createTray(){if(tray)return;const icon=join(projectRoot,"public","pirate-cinema-logo.png");tray=new Tray(icon);tray.setToolTip("Pirate Cinema");tray.setContextMenu(Menu.buildFromTemplate([{label:"Открыть Pirate Cinema",click:showWindow},{type:"separator"},{label:"Выйти",click:()=>{quitting=true;app.quit()}}]));tray.on("double-click",showWindow)}
function createWindow(){const icon=join(projectRoot,"public","pirate-cinema-logo.png");mainWindow=new BrowserWindow({title:"Pirate Cinema",icon,width:1440,height:900,minWidth:1040,minHeight:700,show:false,backgroundColor:"#050505",autoHideMenuBar:true,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,spellcheck:false,preload:join(projectRoot,"electron","preload.cjs")}});mainWindow.webContents.setWindowOpenHandler(({url})=>{if(/^https?:/i.test(url))void shell.openExternal(url);return {action:"deny"}});mainWindow.webContents.on("will-navigate",(event,url)=>{if(!url.startsWith("http://127.0.0.1:3000/")&&!url.startsWith("http://localhost:3000/")){event.preventDefault();if(/^https?:/i.test(url))void shell.openExternal(url)}});mainWindow.on("close",event=>{if(!quitting){event.preventDefault();mainWindow.hide()}});mainWindow.once("ready-to-show",()=>mainWindow?.show());void mainWindow.loadURL("http://127.0.0.1:3000/")}
function stopChildren(){for(const child of children){try{if(!child.killed)child.kill("SIGTERM")}catch{/* A child may already have exited. */}}}
function setUpdateState(next){updateState={...updateState,...next};mainWindow?.webContents.send("update:state",updateState)}
function configureUpdater(){autoUpdater.autoDownload=true;autoUpdater.autoInstallOnAppQuit=true;autoUpdater.on("checking-for-update",()=>setUpdateState({status:"checking",error:null}));autoUpdater.on("update-not-available",()=>setUpdateState({status:"current",version:app.getVersion(),error:null}));autoUpdater.on("update-available",info=>setUpdateState({status:"downloading",version:info.version,error:null}));autoUpdater.on("download-progress",progress=>setUpdateState({status:"downloading",progress:Math.round(progress.percent)}));autoUpdater.on("update-downloaded",info=>setUpdateState({status:"ready",version:info.version,progress:100,error:null}));autoUpdater.on("error",error=>setUpdateState({status:"error",error:error.message}));setTimeout(()=>void autoUpdater.checkForUpdates().catch(()=>{}),5000)}
async function createBackup(){await fetch("http://127.0.0.1:3001/api/maintenance/checkpoint",{method:"POST"});const result=await dialog.showOpenDialog({title:"Куда сохранить резервную копию",properties:["openDirectory","createDirectory"]});if(result.canceled)return null;const stamp=new Date().toISOString().replace(/[:.]/g,"-");const target=join(result.filePaths[0],`Pirate-Cinema-Backup-${stamp}`);mkdirSync(target,{recursive:true});for(const name of ["data","torrserver"]){const source=join(app.getPath("userData"),name);if(existsSync(source))cpSync(source,join(target,name),{recursive:true})}writeFileSync(join(target,"backup.json"),JSON.stringify({application:"Pirate Cinema",version:app.getVersion(),createdAt:new Date().toISOString()},null,2));return target}
async function restoreBackup(){const result=await dialog.showOpenDialog({title:"Выберите папку резервной копии Pirate Cinema",properties:["openDirectory"]});if(result.canceled)return null;const source=result.filePaths[0];if(!existsSync(join(source,"backup.json"))||!existsSync(join(source,"data","media.db")))throw new Error("В выбранной папке нет резервной копии Pirate Cinema");const answer=await dialog.showMessageBox({type:"warning",buttons:["Восстановить и перезапустить","Отмена"],defaultId:1,cancelId:1,title:"Восстановление Pirate Cinema",message:"Текущая медиатека, история и настройки будут заменены резервной копией."});if(answer.response!==0)return null;stopChildren();await new Promise(resolve=>setTimeout(resolve,1500));for(const name of ["data","torrserver"]){const from=join(source,name);if(existsSync(from))cpSync(from,join(app.getPath("userData"),name),{recursive:true,force:true})}app.relaunch();app.exit(0);return true}

if(!app.requestSingleInstanceLock()){app.quit()}else{
  app.on("second-instance",()=>{if(mainWindow){if(mainWindow.isMinimized())mainWindow.restore();mainWindow.focus()}});
  app.on("before-quit",()=>{quitting=true;stopChildren()});
  app.on("window-all-closed",()=>{});
  app.on("activate",()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();else showWindow()});
  app.whenReady().then(async()=>{app.setAppUserModelId("ru.piratecinema.desktop");ipcMain.handle("player:choose",async()=>{const options={title:"Выберите видеоплеер",properties:["openFile"]};if(process.platform==="win32")options.filters=[{name:"Приложения Windows",extensions:["exe"]}];const result=await dialog.showOpenDialog(options);return result.canceled?null:result.filePaths[0]});ipcMain.handle("backup:create",createBackup);ipcMain.handle("backup:restore",restoreBackup);ipcMain.handle("update:status",()=>updateState);ipcMain.handle("update:check",()=>app.isPackaged&&process.platform==="win32"?autoUpdater.checkForUpdates().then(()=>updateState):{...updateState,status:process.platform==="win32"?"development":"unsupported"});ipcMain.handle("update:install",()=>autoUpdater.quitAndInstall(false,true));try{await startServices();createWindow();createTray();if(app.isPackaged&&process.platform==="win32")configureUpdater()}catch(error){log(error instanceof Error?error.stack??error.message:String(error));await dialog.showMessageBox({type:"error",title:"Pirate Cinema не запустился",message:"Не удалось запустить локальные сервисы",detail:error instanceof Error?error.message:String(error)});if(!quitting)app.quit()}});
}
