"use client";

import {useEffect,useMemo,useState} from "react";
import {Capacitor,registerPlugin} from "@capacitor/core";
import {Backspace,Check,CircleNotch,FilmStrip,GearSix,House,Keyboard,LinkSimple,Magnet,MagnifyingGlass,Play,Plus,SlidersHorizontal,X} from "@phosphor-icons/react";
import {enableRutorSearch,mpvIntent,normalizeTorrent,playbackHistoryEntry,streamUrl,torrentFiles} from "./torrserver.mjs";
import styles from "./mobile.module.css";

type File={id:number;path:string;name:string;length:number};
type Media={hash:string;title:string;poster:string;files:File[]};
type SearchItem={title:string;magnet:string;size:string;seeders:number};
type Section="home"|"search"|"library"|"settings";
type Player="mpv"|"system";
type HistoryEntry={hash:string;fileId:number;fileName:string;title:string;positionMs:number;durationMs:number;completed:boolean;lastPlayedAt:string};
const DEFAULT_SERVER="http://127.0.0.1:8090";
const TONES=["moon","city","sun","forest","ocean"];
const ExternalPlayer=registerPlugin<{open(options:{url:string;title:string;preferred:Player;positionMs:number}):Promise<{ok:boolean;positionMs?:number;durationMs?:number;completed?:boolean}>}>("ExternalPlayer");

function cleanServer(value:string){const url=new URL(value.trim());if(!["http:","https:"].includes(url.protocol))throw new Error("Нужен HTTP(S)-адрес");return url.toString().replace(/\/$/,"")}
function magnetTitle(value:string){try{return new URL(value).searchParams.get("dn")?.trim()||"Magnet-раздача"}catch{return "Magnet-раздача"}}
function formatTime(value:number){const seconds=Math.floor(Math.max(0,value)/1000),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60),rest=seconds%60;return hours?`${hours}:${String(minutes).padStart(2,"0")}:${String(rest).padStart(2,"0")}`:`${minutes}:${String(rest).padStart(2,"0")}`}

function VirtualKeyboard({value,onChange,onSubmit,onClose}:{value:string;onChange:(value:string)=>void;onSubmit:()=>void;onClose:()=>void}){
  const [layout,setLayout]=useState<"ru"|"en">("ru");
  const rows=layout==="ru"?["йцукенгшщзхъ","фывапролджэ","ячсмитьбю"]:["qwertyuiop","asdfghjkl","zxcvbnm"];
  return <section className={styles.keyboard} aria-label="Экранная клавиатура"><header><span><Keyboard size={17}/>Клавиатура</span><button onClick={onClose}><X size={18}/></button></header>{rows.map(row=><div className={styles.keyRow} key={row}>{[...row].map(key=><button key={key} onClick={()=>onChange(value+key)}>{key}</button>)}</div>)}<div className={styles.keyRow}><button className={styles.langKey} onClick={()=>setLayout(layout==="ru"?"en":"ru")}>{layout.toUpperCase()}</button><button className={styles.spaceKey} onClick={()=>onChange(value+" ")}>пробел</button><button onClick={()=>onChange(value.slice(0,-1))} aria-label="Удалить символ"><Backspace size={19}/></button><button className={styles.enterKey} onClick={onSubmit}>Найти</button></div></section>;
}

export default function MobilePrototype(){
  const [section,setSection]=useState<Section>("home"),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[items,setItems]=useState<Media[]>([]),[results,setResults]=useState<SearchItem[]>([]),[selected,setSelected]=useState<Media|null>(null),[file,setFile]=useState<File|null>(null),[player,setPlayer]=useState<Player>("mpv"),[preferredPlayer,setPreferredPlayer]=useState<Player>("mpv"),[history,setHistory]=useState<Record<string,HistoryEntry>>({}),[keyboardOpen,setKeyboardOpen]=useState(false),[magnetOpen,setMagnetOpen]=useState(false),[magnet,setMagnet]=useState(""),[serverUrl,setServerUrl]=useState(DEFAULT_SERVER),[serverVersion,setServerVersion]=useState(""),[rutorEnabled,setRutorEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");
  const online=Boolean(serverVersion);
  const visible=useMemo(()=>items.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||(filter==="movie"&&item.files.length<=1)||(filter==="series"&&item.files.length>1))),[filter,items,query]);
  const historyItems=useMemo(()=>Object.values(history).sort((a,b)=>b.lastPlayedAt.localeCompare(a.lastPlayedAt)),[history]);
  const continuing=historyItems.find(entry=>!entry.completed&&entry.positionMs>0&&items.some(item=>item.hash===entry.hash));
  const currentHistory=selected&&file?history[`${selected.hash}:${file.id}`]:null;
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};

  async function readSettings(base=serverUrl){const response=await fetch(`${base}/settings`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"get"})});if(!response.ok)throw new Error(`Настройки TorrServer: ${response.status}`);return response.json()}
  async function ensureRutor(){const settings=enableRutorSearch(await readSettings());if(settings){const response=await fetch(`${serverUrl}/settings`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"set",sets:settings})});if(!response.ok)throw new Error(`Не удалось включить RuTor: ${response.status}`)}setRutorEnabled(true)}
  async function connect(value=serverUrl){setBusy(true);setError("");try{const base=cleanServer(value);const [echo,response,settings]=await Promise.all([fetch(`${base}/echo`).then(result=>{if(!result.ok)throw new Error(`TorrServer ${result.status}`);return result.text()}),fetch(`${base}/torrents`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list"})}),readSettings(base).catch(()=>null)]);if(!response.ok)throw new Error(`TorrServer ${response.status}`);const payload=await response.json();setServerUrl(base);setServerVersion(String(echo).trim());setRutorEnabled(Boolean(settings?.EnableRutorSearch));setItems((Array.isArray(payload)?payload:payload?.torrents??payload?.items??[]).map(normalizeTorrent).filter((item:Media)=>item.hash));return true}catch(reason){setServerVersion("");setItems([]);setError(reason instanceof Error?reason.message:"TorrServer не отвечает");return false}finally{setBusy(false)}}
  useEffect(()=>{const saved=window.localStorage.getItem("pirate-cinema-mobile-server")||DEFAULT_SERVER;const savedPlayer=window.localStorage.getItem("pirate-cinema-mobile-player")==="system"?"system":"mpv";let savedHistory:Record<string,HistoryEntry>={};try{savedHistory=JSON.parse(window.localStorage.getItem("pirate-cinema-mobile-history")||"{}")}catch{savedHistory={}}queueMicrotask(()=>{setPreferredPlayer(savedPlayer);setHistory(savedHistory);void connect(saved)})},[]);// eslint-disable-line react-hooks/exhaustive-deps

  function choosePlayer(value:Player){setPlayer(value);setPreferredPlayer(value);window.localStorage.setItem("pirate-cinema-mobile-player",value)}
  async function open(item:Media,fileId?:number){setBusy(true);setError("");setKeyboardOpen(false);try{let files=item.files;if(!files.length){const response=await fetch(`${serverUrl}/stream/details?link=${encodeURIComponent(item.hash)}&stat`);if(!response.ok)throw new Error(`TorrServer ${response.status}`);files=torrentFiles(await response.json())}if(!files.length)throw new Error("В раздаче не найдены видеофайлы");setSelected({...item,files});setFile(files.find(value=>value.id===fileId)??files[0]);setPlayer(preferredPlayer)}catch(reason){notify(reason instanceof Error?reason.message:"Не удалось получить файлы")}finally{setBusy(false)}}
  async function launch(mode:"resume"|"start"="resume"){if(!selected||!file)return;const url=streamUrl(serverUrl,selected.hash,file),title=selected.title,key=`${selected.hash}:${file.id}`,saved=history[key];try{if(Capacitor.isNativePlatform()){const result=await ExternalPlayer.open({url,title,preferred:player,positionMs:mode==="resume"?saved?.positionMs??0:0});const entry=playbackHistoryEntry(saved,result,{hash:selected.hash,fileId:file.id,fileName:file.name,title});if(entry){const next={...history,[key]:entry};setHistory(next);window.localStorage.setItem("pirate-cinema-mobile-history",JSON.stringify(next))}}else if(player==="mpv")window.location.href=mpvIntent(url,title);else{const opened=window.open(url,"_blank","noopener,noreferrer");if(!opened)window.location.href=url}setSelected(null)}catch(reason){notify(reason instanceof Error?reason.message:"Не удалось открыть внешний плеер")}}
  async function add(value=magnet,title=magnetTitle(value)){const clean=value.trim();if(!/^magnet:\?/.test(clean)||!/[?&]xt=urn:btih:(?:[a-f\d]{40}|[a-z2-7]{32})/i.test(clean)){setError("Нужна корректная magnet-ссылка с BTIH hash");return}setBusy(true);setError("");try{const response=await fetch(`${serverUrl}/torrents`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add",link:clean,title,save_to_db:true})});if(!response.ok)throw new Error(`TorrServer ${response.status}`);setMagnet("");setMagnetOpen(false);await connect();notify("Раздача добавлена в TorrServer")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось добавить раздачу")}finally{setBusy(false)}}
  async function search(){const clean=query.trim();if(clean.length<2)return;setBusy(true);setError("");setKeyboardOpen(false);try{await ensureRutor();const response=await fetch(`${serverUrl}/search/?query=${encodeURIComponent(clean)}`);if(!response.ok)throw new Error(`Поиск TorrServer: ${response.status}`);const payload=await response.json();setResults((Array.isArray(payload)?payload:[]).map(raw=>({title:String(raw.Title??raw.title??raw.Name??"Без названия"),magnet:String(raw.Magnet??raw.magnet??raw.Link??raw.link??""),size:String(raw.Size??raw.size??"—"),seeders:Number(raw.Seed??raw.seed??raw.seeders??0)})).filter(item=>item.magnet).slice(0,60))}catch(reason){setError(reason instanceof TypeError?"Поиск TorrServer недоступен":reason instanceof Error?reason.message:"Поиск недоступен")}finally{setBusy(false)}}
  async function saveServer(){try{const base=cleanServer(serverUrl);window.localStorage.setItem("pirate-cinema-mobile-server",base);if(await connect(base))notify("TorrServer подключён")}catch(reason){setError(reason instanceof Error?reason.message:"Некорректный адрес")}}
  function navigate(next:Section){setSection(next);setQuery("");setKeyboardOpen(false);setError("")}

  const status=<button className={styles.server} onClick={()=>connect()}><span>{busy?<CircleNotch className={styles.spin} size={22}/>:online?<Check size={22} weight="bold"/>:<X size={22}/>}</span><div><strong>{online?"TorrServer готов":"TorrServer недоступен"}</strong><small>{online?`${items.length} раздач · RuTor ${rutorEnabled?"включён":"будет включён при поиске"}`:serverUrl}</small></div></button>;
  const mediaList=(list:Media[])=><div className={styles.list}>{list.map((item,index)=>{const saved=historyItems.find(entry=>entry.hash===item.hash);return <article key={item.hash}><button className={`${styles.thumb} ${styles[TONES[index%TONES.length]]}`} onClick={()=>open(item,saved?.fileId)} aria-label={`Открыть ${item.title}`}><Play size={22} weight="fill"/></button><button className={styles.info} onClick={()=>open(item,saved?.fileId)}><strong>{item.title}</strong><small>{saved?saved.completed?"Просмотрено":`Продолжить с ${formatTime(saved.positionMs)}`:item.files.length?`${item.files.length} видеофайл${item.files.length===1?"":"а"}`:"Получить список файлов"}</small>{saved?.durationMs>0&&<i className={styles.historyProgress}><b style={{width:`${saved.completed?100:Math.min(100,saved.positionMs/saved.durationMs*100)}%`}}/></i>}</button><button className={styles.play} onClick={()=>open(item,saved?.fileId)} aria-label={`Воспроизвести ${item.title}`}><Play size={19} weight="fill"/></button></article>})}</div>;

  return <main className={styles.stage}><section className={styles.phone}>
    <header className={styles.header}><div><span>ANDROID</span><h1>Pirate Cinema</h1></div><button className={styles.status} onClick={()=>connect()}><i className={online?"":styles.offline}/>{online?serverVersion:"Не подключён"}</button></header>
    {section==="home"&&<section className={styles.home}>{status}<div className={styles.hero}><span>ЛОКАЛЬНЫЙ КИНОТЕАТР</span><h2>{items.length?"Всё готово к просмотру":"Добавьте первый фильм"}</h2><p>{items.length?`В TorrServer сохранено ${items.length}. Выберите недавнюю раздачу или найдите новую.`:"Найдите раздачу через RuTor или вставьте magnet-ссылку."}</p><div><button onClick={()=>navigate("search")}><MagnifyingGlass size={19}/>Найти фильм</button><button onClick={()=>setMagnetOpen(true)}><Magnet size={19}/>Magnet</button></div></div>{continuing&&<button className={styles.continueCard} onClick={()=>{const item=items.find(value=>value.hash===continuing.hash);if(item)void open(item,continuing.fileId)}}><span><Play size={22} weight="fill"/></span><div><small>ПРОДОЛЖИТЬ ПРОСМОТР</small><strong>{continuing.title}</strong><em>{continuing.fileName} · {formatTime(continuing.positionMs)}</em></div></button>}{items.length?<><div className={styles.sectionTitle}><strong>Недавно добавленные</strong><button onClick={()=>navigate("library")}>Все</button></div>{mediaList(items.slice(0,continuing?2:3))}</>:<div className={styles.emptyHome}><FilmStrip size={30}/><strong>Медиатека пока пуста</strong><span>Поиск RuTor уже доступен внутри приложения.</span></div>}</section>}
    {section==="search"&&<section className={styles.page}>{status}<span className={styles.eyebrow}>ПОИСК TORRSERVER</span><h2>Найти раздачу</h2><form className={styles.search} onSubmit={event=>{event.preventDefault();void search()}}><MagnifyingGlass size={23}/><input inputMode="none" value={query} onFocus={()=>setKeyboardOpen(true)} onChange={event=>setQuery(event.target.value)} placeholder="Название фильма или сериала"/><button type="submit" aria-label="Найти"><Play size={18} weight="fill"/></button></form><div className={styles.results}><p>{results.length?`Найдено: ${results.length}`:"Введите название и нажмите «Найти»"}</p>{results.map((item,index)=><article key={`${item.title}-${index}`}><div><strong>{item.title}</strong><small>{item.size} · {item.seeders} сидов</small></div><button disabled={busy} onClick={()=>add(item.magnet,item.title)}><Plus size={18}/>Добавить</button></article>)}</div></section>}
    {section==="library"&&<section className={styles.page}>{status}<span className={styles.eyebrow}>МЕДИАТЕКА</span><h2>Сохранённые раздачи</h2><div className={styles.search}><MagnifyingGlass size={23}/><input inputMode="none" value={query} onFocus={()=>setKeyboardOpen(true)} onChange={event=>setQuery(event.target.value)} placeholder="Фильтр по названию"/>{query&&<button onClick={()=>setQuery("")}><X size={18}/></button>}</div><div className={styles.filters}><button className={filter==="all"?styles.chosen:""} onClick={()=>setFilter("all")}>Все</button><button className={filter==="movie"?styles.chosen:""} onClick={()=>setFilter("movie")}>Один файл</button><button className={filter==="series"?styles.chosen:""} onClick={()=>setFilter("series")}>Несколько файлов</button></div>{visible.length?mediaList(visible):<p className={styles.empty}>В медиатеке пока ничего нет</p>}</section>}
    {section==="settings"&&<section className={styles.settings}><span className={styles.eyebrow}>НАСТРОЙКИ</span><h2>Подключение</h2>{status}<label>Адрес TorrServer<input value={serverUrl} onChange={event=>setServerUrl(event.target.value)}/></label><button className={styles.check} disabled={busy} onClick={saveServer}>{busy?<CircleNotch className={styles.spin} size={19}/>:<LinkSimple size={19}/>}Сохранить и проверить</button><h3>Плеер по умолчанию</h3><div className={styles.players}><button className={preferredPlayer==="mpv"?styles.selectedPlayer:""} onClick={()=>choosePlayer("mpv")}><span><Play size={20} weight="fill"/></span><div><strong>mpv-android</strong><small>Рекомендуемый вариант</small></div>{preferredPlayer==="mpv"&&<Check size={20}/>}</button><button className={preferredPlayer==="system"?styles.selectedPlayer:""} onClick={()=>choosePlayer("system")}><span><SlidersHorizontal size={20}/></span><div><strong>Открыть с помощью</strong><small>Системный выбор приложения</small></div>{preferredPlayer==="system"&&<Check size={20}/>}</button></div></section>}
    <button className={styles.fab} onClick={()=>{setError("");setKeyboardOpen(false);setMagnetOpen(true)}} aria-label="Добавить magnet-ссылку"><Plus size={27}/></button>
    <nav className={styles.nav}><button className={section==="home"?styles.current:""} onClick={()=>navigate("home")}><House size={23} weight={section==="home"?"fill":"regular"}/>Главная</button><button className={section==="search"?styles.current:""} onClick={()=>navigate("search")}><MagnifyingGlass size={23}/>Поиск</button><button className={section==="library"?styles.current:""} onClick={()=>navigate("library")}><FilmStrip size={23}/>Медиатека</button><button className={section==="settings"?styles.current:""} onClick={()=>navigate("settings")}><GearSix size={23}/>Настройки</button></nav>
    {keyboardOpen&&!selected&&!magnetOpen&&<VirtualKeyboard value={query} onChange={setQuery} onSubmit={()=>void search()} onClose={()=>setKeyboardOpen(false)}/>}
    {selected&&file&&<div className={styles.overlay}><button className={styles.backdrop} onClick={()=>setSelected(null)} aria-label="Закрыть выбор плеера"/><section className={styles.sheet}><button className={styles.close} onClick={()=>setSelected(null)}><X size={22}/></button><span className={styles.eyebrow}>ВОСПРОИЗВЕДЕНИЕ</span><h2>{selected.title}</h2><label>Файл<select value={file.id} onChange={event=>setFile(selected.files.find(item=>item.id===Number(event.target.value))??selected.files[0])}>{selected.files.map(value=>{const saved=history[`${selected.hash}:${value.id}`];return <option key={value.id} value={value.id}>{value.name}{saved?` · ${saved.completed?"просмотрено":formatTime(saved.positionMs)}`:""}</option>})}</select></label>{currentHistory&&<p className={styles.resumeInfo}>{currentHistory.completed?"Файл просмотрен":`Остановились на ${formatTime(currentHistory.positionMs)} из ${formatTime(currentHistory.durationMs)}`}</p>}<div className={styles.players}><button className={player==="mpv"?styles.selectedPlayer:""} onClick={()=>choosePlayer("mpv")}><span><Play size={20} weight="fill"/></span><div><strong>mpv-android</strong><small>Сохраняет точную позицию</small></div>{player==="mpv"&&<Check size={20}/>}</button><button className={player==="system"?styles.selectedPlayer:""} onClick={()=>choosePlayer("system")}><span><SlidersHorizontal size={20}/></span><div><strong>Открыть с помощью</strong><small>История зависит от выбранного плеера</small></div>{player==="system"&&<Check size={20}/>}</button></div><div className={styles.playActions}>{currentHistory&&!currentHistory.completed&&currentHistory.positionMs>0&&<button className={styles.primary} onClick={()=>launch("resume")}><Play size={19} weight="fill"/>Продолжить с {formatTime(currentHistory.positionMs)}</button>}<button className={currentHistory&&!currentHistory.completed&&currentHistory.positionMs>0?styles.secondary:styles.primary} onClick={()=>launch("start")}><Play size={19} weight="fill"/>{currentHistory?"Сначала":"Воспроизвести"}</button></div></section></div>}
    {magnetOpen&&<div className={styles.overlay}><button className={styles.backdrop} onClick={()=>setMagnetOpen(false)} aria-label="Закрыть добавление раздачи"/><section className={styles.sheet}><button className={styles.close} onClick={()=>setMagnetOpen(false)}><X size={22}/></button><span className={styles.eyebrow}>TORRSERVER</span><h2>Добавить раздачу</h2><label>Magnet-ссылка<textarea value={magnet} onChange={event=>setMagnet(event.target.value)} placeholder="magnet:?xt=urn:btih:…"/></label><button className={styles.primary} disabled={busy} onClick={()=>add()}><Magnet size={19}/>Добавить</button></section></div>}
    {error&&<div className={styles.error} role="alert"><X size={18}/>{error}</div>}{toast&&<div className={styles.toast}><Check size={18}/>{toast}</div>}
  </section></main>;
}
