"use client";

import {useEffect,useMemo,useState} from "react";
import {Check,CircleNotch,FilmStrip,GearSix,House,LinkSimple,Magnet,MagnifyingGlass,Play,Plus,SlidersHorizontal,X} from "@phosphor-icons/react";
import {mpvIntent,normalizeTorrent,streamUrl,torrentFiles} from "./torrserver.mjs";
import styles from "./mobile.module.css";

type File={id:number;path:string;name:string;length:number};
type Media={hash:string;title:string;poster:string;files:File[]};
type SearchItem={title:string;magnet:string;size:string};
const DEFAULT_SERVER="http://127.0.0.1:8090";
const TONES=["moon","city","sun","forest","ocean"];

function cleanServer(value:string){const url=new URL(value.trim());if(!["http:","https:"].includes(url.protocol))throw new Error("Нужен HTTP(S)-адрес");return url.toString().replace(/\/$/,"")}
function magnetTitle(value:string){try{return new URL(value).searchParams.get("dn")?.trim()||"Magnet-раздача"}catch{return "Magnet-раздача"}}

export default function MobilePrototype(){
  const [section,setSection]=useState<"home"|"library"|"settings">("home"),[mode,setMode]=useState<"library"|"search">("library"),[filter,setFilter]=useState("all"),[query,setQuery]=useState(""),[items,setItems]=useState<Media[]>([]),[results,setResults]=useState<SearchItem[]>([]),[selected,setSelected]=useState<Media|null>(null),[file,setFile]=useState<File|null>(null),[player,setPlayer]=useState<"mpv"|"system">("mpv"),[magnetOpen,setMagnetOpen]=useState(false),[magnet,setMagnet]=useState(""),[serverUrl,setServerUrl]=useState(DEFAULT_SERVER),[serverVersion,setServerVersion]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[toast,setToast]=useState("");
  const online=Boolean(serverVersion);
  const visible=useMemo(()=>items.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())&&(filter==="all"||(filter==="movie"&&item.files.length<=1)||(filter==="series"&&item.files.length>1))),[filter,items,query]);
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  async function connect(value=serverUrl){setBusy(true);setError("");try{const base=cleanServer(value);const [echo,response]=await Promise.all([fetch(`${base}/echo`).then(result=>{if(!result.ok)throw new Error(`TorrServer ${result.status}`);return result.text()}),fetch(`${base}/torrents`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"list"})})]);if(!response.ok)throw new Error(`TorrServer ${response.status}`);const payload=await response.json();setServerUrl(base);setServerVersion(String(echo).trim());setItems((Array.isArray(payload)?payload:payload?.torrents??payload?.items??[]).map(normalizeTorrent).filter((item:Media)=>item.hash));return true}catch(reason){setServerVersion("");setItems([]);setError(reason instanceof Error?reason.message:"TorrServer не отвечает");return false}finally{setBusy(false)}}
  // The saved endpoint is intentionally read only once on first mount.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const saved=window.localStorage.getItem("pirate-cinema-mobile-server")||DEFAULT_SERVER;queueMicrotask(()=>void connect(saved))},[]);
  async function open(item:Media){setBusy(true);setError("");try{let files=item.files;if(!files.length){const response=await fetch(`${serverUrl}/stream/details?link=${encodeURIComponent(item.hash)}&stat`);if(!response.ok)throw new Error(`TorrServer ${response.status}`);files=torrentFiles(await response.json())}if(!files.length)throw new Error("В раздаче не найдены видеофайлы");setSelected({...item,files});setFile(files[0]);setPlayer("mpv")}catch(reason){notify(reason instanceof Error?reason.message:"Не удалось получить файлы")}finally{setBusy(false)}}
  function launch(){if(!selected||!file)return;const url=streamUrl(serverUrl,selected.hash,file);setSelected(null);if(player==="mpv")window.location.href=mpvIntent(url,selected.title);else{const opened=window.open(url,"_blank","noopener,noreferrer");if(!opened)window.location.href=url}}
  async function add(value=magnet,title=magnetTitle(value)){const clean=value.trim();if(!/^magnet:\?/.test(clean)||!/[?&]xt=urn:btih:(?:[a-f\d]{40}|[a-z2-7]{32})/i.test(clean)){setError("Нужна корректная magnet-ссылка с BTIH hash");return}setBusy(true);setError("");try{const response=await fetch(`${serverUrl}/torrents`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"add",link:clean,title,save_to_db:true})});if(!response.ok)throw new Error(`TorrServer ${response.status}`);setMagnet("");setMagnetOpen(false);await connect();notify("Раздача добавлена в TorrServer")}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось добавить раздачу")}finally{setBusy(false)}}
  async function search(){const clean=query.trim();if(clean.length<2)return;setBusy(true);setError("");try{const response=await fetch(`${serverUrl}/search/?query=${encodeURIComponent(clean)}`);if(!response.ok&&response.status!==400)throw new Error(`TorrServer ${response.status}`);const payload=await response.json();setResults((Array.isArray(payload)?payload:[]).map(raw=>({title:String(raw.Title??raw.title??raw.Name??"Без названия"),magnet:String(raw.Magnet??raw.magnet??raw.Link??raw.link??""),size:String(raw.Size??raw.size??"—")})).filter(item=>item.magnet));setMode("search")}catch(reason){setError(reason instanceof TypeError?"Поиск TorrServer недоступен":reason instanceof Error?reason.message:"Поиск недоступен")}finally{setBusy(false)}}
  async function saveServer(){try{const base=cleanServer(serverUrl);window.localStorage.setItem("pirate-cinema-mobile-server",base);if(await connect(base))notify("TorrServer подключён")}catch(reason){setError(reason instanceof Error?reason.message:"Некорректный адрес")}}
  return <main className={styles.stage}><section className={styles.phone}>
    <header className={styles.header}><div><span>ANDROID MVP</span><h1>Pirate Cinema</h1></div><button className={styles.status} onClick={()=>connect()}><i className={online?"":styles.offline}/>{online?serverVersion:"Не подключён"}</button></header>
    {section!=="settings"?<>
      <button className={styles.server} onClick={()=>connect()}><span>{busy?<CircleNotch className={styles.spin} size={22}/>:online?<Check size={22} weight="bold"/>:<X size={22}/>}</span><div><strong>{online?"TorrServer готов":"TorrServer недоступен"}</strong><small>{online?`${items.length} раздач в медиатеке`:serverUrl}</small></div></button>
      <div className={styles.segment}><button className={mode==="library"?styles.active:""} onClick={()=>setMode("library")}>Медиатека</button><button className={mode==="search"?styles.active:""} onClick={()=>setMode("search")}>Поиск</button></div>
      <form className={styles.search} onSubmit={event=>{event.preventDefault();if(mode==="search")void search()}}><MagnifyingGlass size={23}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={mode==="search"?"Название фильма или сериала":"Название в медиатеке"}/>{query&&<button type="button" onClick={()=>setQuery("")}><X size={18}/></button>}</form>
      {mode==="library"?<><div className={styles.filters}><button className={filter==="all"?styles.chosen:""} onClick={()=>setFilter("all")}>Все</button><button className={filter==="movie"?styles.chosen:""} onClick={()=>setFilter("movie")}>Один файл</button><button className={filter==="series"?styles.chosen:""} onClick={()=>setFilter("series")}>Несколько файлов</button></div><div className={styles.list}>{visible.map((item,index)=><article key={item.hash}><button className={`${styles.thumb} ${styles[TONES[index%TONES.length]]}`} onClick={()=>open(item)} aria-label={`Открыть ${item.title}`}><Play size={22} weight="fill"/></button><button className={styles.info} onClick={()=>open(item)}><strong>{item.title}</strong><small>{item.files.length?`${item.files.length} видеофайл${item.files.length===1?"":"а"}`:"Получить список файлов"}</small></button><button className={styles.play} onClick={()=>open(item)} aria-label={`Воспроизвести ${item.title}`}><Play size={19} weight="fill"/></button></article>)}{online&&!visible.length&&<p className={styles.empty}>В медиатеке пока ничего нет</p>}</div></>:<div className={styles.results}><p>{results.length?`Найдено: ${results.length}`:"Введите название и нажмите Enter"}</p>{results.map((item,index)=><article key={`${item.title}-${index}`}><div><strong>{item.title}</strong><small>{item.size}</small></div><button disabled={busy} onClick={()=>add(item.magnet,item.title)}><Plus size={18}/>Добавить</button></article>)}</div>}
      <button className={styles.fab} onClick={()=>{setError("");setMagnetOpen(true)}} aria-label="Добавить magnet-ссылку"><Plus size={27}/></button>
    </>:<section className={styles.settings}><span className={styles.eyebrow}>НАСТРОЙКИ</span><h2>Подключение</h2><label>Адрес TorrServer<input value={serverUrl} onChange={event=>setServerUrl(event.target.value)}/></label><button className={styles.check} disabled={busy} onClick={saveServer}>{busy?<CircleNotch className={styles.spin} size={19}/>:<LinkSimple size={19}/>}Сохранить и проверить</button><div className={styles.settingCard}><span><Play size={21} weight="fill"/></span><div><strong>mpv-android</strong><small>Рекомендуемый внешний плеер</small></div><Check size={20}/></div><p>Для TorrServer на другом устройстве укажите его адрес в локальной сети.</p></section>}
    <nav className={styles.nav}><button className={section==="home"?styles.current:""} onClick={()=>{setSection("home");setMode("library")}}><House size={24} weight={section==="home"?"fill":"regular"}/>Главная</button><button className={section==="library"?styles.current:""} onClick={()=>{setSection("library");setMode("library")}}><FilmStrip size={24}/>Медиатека</button><button className={section==="settings"?styles.current:""} onClick={()=>setSection("settings")}><GearSix size={24}/>Настройки</button></nav>
    {selected&&file&&<div className={styles.overlay}><button className={styles.backdrop} onClick={()=>setSelected(null)} aria-label="Закрыть выбор плеера"/><section className={styles.sheet}><button className={styles.close} onClick={()=>setSelected(null)}><X size={22}/></button><span className={styles.eyebrow}>ВОСПРОИЗВЕДЕНИЕ</span><h2>{selected.title}</h2><label>Файл<select value={file.id} onChange={event=>setFile(selected.files.find(item=>item.id===Number(event.target.value))??selected.files[0])}>{selected.files.map(value=><option key={value.id} value={value.id}>{value.name}</option>)}</select></label><div className={styles.players}><button className={player==="mpv"?styles.selectedPlayer:""} onClick={()=>setPlayer("mpv")}><span><Play size={20} weight="fill"/></span><div><strong>mpv-android</strong><small>Рекомендуемый вариант</small></div>{player==="mpv"&&<Check size={20}/>}</button><button className={player==="system"?styles.selectedPlayer:""} onClick={()=>setPlayer("system")}><span><SlidersHorizontal size={20}/></span><div><strong>Открыть с помощью</strong><small>Системный выбор плеера</small></div>{player==="system"&&<Check size={20}/>}</button></div><button className={styles.primary} onClick={launch}><Play size={19} weight="fill"/>Воспроизвести</button></section></div>}
    {magnetOpen&&<div className={styles.overlay}><button className={styles.backdrop} onClick={()=>setMagnetOpen(false)} aria-label="Закрыть добавление раздачи"/><section className={styles.sheet}><button className={styles.close} onClick={()=>setMagnetOpen(false)}><X size={22}/></button><span className={styles.eyebrow}>TORRSERVER</span><h2>Добавить раздачу</h2><label>Magnet-ссылка<textarea value={magnet} onChange={event=>setMagnet(event.target.value)} placeholder="magnet:?xt=urn:btih:…"/></label><button className={styles.primary} disabled={busy} onClick={()=>add()}><Magnet size={19}/>Добавить</button></section></div>}
    {error&&<div className={styles.error} role="alert"><X size={18}/>{error}</div>}{toast&&<div className={styles.toast}><Check size={18}/>{toast}</div>}
  </section></main>
}
