"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import {Books,Check,CircleNotch,Database,FilmStrip,GearSix,HardDrives,House,Magnet,MagnifyingGlass,Play,Plus,Pulse,SlidersHorizontal,Trash} from "@phosphor-icons/react";
import {MediaFilePicker,PlaybackBar,WikipediaCredit,type TorrentFile} from "./Playback";
import {PlayerPreferences,Welcome,type Preferences} from "./Preferences";
import {version as appVersion} from "../package.json";

const API="http://127.0.0.1:3001";
type Media={overview?:string;overviewSourceUrl?:string|null;runtimeSeconds?:number|null;torrentHash:string;torrentName:string;title:string;year:number|null;mediaType:string;posterPath:string|null;posterUrl:string|null;rating:number|null;genres:string[];progress:number|null;isActive:boolean;peers:number;addedAt:string};
type AppState={syncProgress?:{processed:number;total:number;failed:number;full:boolean};lastSync?:string|null;online:boolean;syncing:boolean;serverVersion:string|null;torrServerUrl:string;metadataMode:"tmdb"|"open"|"local";error:string|null;searchProviders?:string[]};
type LibraryPayload={state:AppState;stats:{total:number;active:number;continuing:number};items:Media[];continueWatching:Media[];recentlyAdded:Media[]};
type Details={provider?:string;providerId?:string;title:string;originalTitle?:string;year:number|null;type?:string;posterUrl?:string|null;backdropUrl?:string|null;runtimeSeconds?:number|null;rating?:number|null;genres?:string[];overview?:string;overviewSourceUrl?:string|null;gallery?:string[]};
type Release={title:string;size:string;seeders:number;peers:number;magnet:string;hash:string;tracker:string;source?:string;year:number|null;quality:string};
type SearchPayload={query:string;metadata:Details|null;results:Release[]};
type TopMovie={rank:number;imdbId:string;title:string;originalTitle:string;year:number;rating:number;posterUrl?:string};
const EMPTY:LibraryPayload={state:{online:false,syncing:true,serverVersion:null,torrServerUrl:"http://127.0.0.1:8090",metadataMode:"local",error:null},stats:{total:0,active:0,continuing:0},items:[],continueWatching:[],recentlyAdded:[]};
const TOP_MOVIES:TopMovie[]=[
  {rank:1,imdbId:"kp8484833",title:"Последний богатырь. Колобок",originalTitle:"Последний богатырь. Колобок",year:2026,rating:3.0,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_8484833.jpg"},{rank:2,imdbId:"kp5494049",title:"Человек-паук: Новый день",originalTitle:"Spider-Man: Brand New Day",year:2026,rating:8.2,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_5494049.jpg"},{rank:3,imdbId:"kp6385370",title:"Одиссея",originalTitle:"The Odyssey",year:2026,rating:8.3,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_6385370.jpg"},{rank:4,imdbId:"kp7036356",title:"Холод",originalTitle:"Холод",year:2026,rating:7.9,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_7036356.jpg"},{rank:5,imdbId:"kp10355286",title:"Обсессия",originalTitle:"Obsession",year:2025,rating:7.1,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_10355286.jpg"},
  {rank:6,imdbId:"kp6135670",title:"Смешарики сквозь вселенные",originalTitle:"Смешарики сквозь вселенные",year:2026,rating:6.5,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_6135670.jpg"},{rank:7,imdbId:"kp1316601",title:"Дом Дракона",originalTitle:"House of the Dragon",year:2022,rating:8.1,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_1316601.jpg"},{rank:8,imdbId:"kp5452841",title:"Закулисье реальности",originalTitle:"Backrooms",year:2026,rating:6.5,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_5452841.jpg"},{rank:9,imdbId:"kp5138994",title:"Приглашение",originalTitle:"The Invite",year:2026,rating:7.0,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_5138994.jpg"},{rank:10,imdbId:"kp5437614",title:"Майкл",originalTitle:"Michael",year:2026,rating:7.8,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_5437614.jpg"},
  {rank:11,imdbId:"kp4541515",title:"Укрытие",originalTitle:"Silo",year:2023,rating:7.8,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_4541515.jpg"},{rank:12,imdbId:"kp820638",title:"Мажор",originalTitle:"Мажор",year:2014,rating:8.2,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_820638.jpg"},{rank:13,imdbId:"tt12042730",title:"Проект «Конец света»",originalTitle:"Project Hail Mary",year:2026,rating:8.4},{rank:14,imdbId:"kp8290235",title:"Твоё сердце будет разбито",originalTitle:"Твоё сердце будет разбито",year:2026,rating:7.5,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_8290235.jpg"},{rank:15,imdbId:"kp464963",title:"Игра престолов",originalTitle:"Game of Thrones",year:2011,rating:9.0,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_464963.jpg"},
  {rank:16,imdbId:"kp940680",title:"Ольга",originalTitle:"Ольга",year:2016,rating:6.6,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_940680.jpg"},{rank:17,imdbId:"kp6943600",title:"Последний дом",originalTitle:"The Last House",year:2026,rating:5.9,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_6943600.jpg"},{rank:18,imdbId:"kp1309570",title:"Человек-паук: Нет пути домой",originalTitle:"Spider-Man: No Way Home",year:2021,rating:7.9,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_1309570.jpg"},{rank:19,imdbId:"kp958607",title:"Леди Баг и Супер-Кот",originalTitle:"Miraculous: Tales of Ladybug & Cat Noir",year:2015,rating:8.3,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_958607.jpg"},{rank:20,imdbId:"kp11272092",title:"История его служанки",originalTitle:"История его служанки",year:2026,rating:7.4,posterUrl:"https://st.kp.yandex.net/images/film_iphone/iphone360_11272092.jpg"}
];
function imageSrc(value?:string|null){if(!value)return null;return value.startsWith("/api/")?`${API}${value}`:value}
function seconds(value?:number|null){if(!value)return null;const h=Math.floor(value/3600),m=Math.round(value%3600/60);return h?`${h} ч ${m} мин`:`${m} мин`}
function isMagnetInput(value:string){return value.toLowerCase().includes("magnet:?")}
function releaseFromMagnet(value:string):Release{const clean=value.trim().replace(/&amp;/gi,"&");const offset=clean.toLowerCase().indexOf("magnet:?");const magnet=offset>=0?clean.slice(offset).replace(/^['"]+|['"]+$/g,""):clean;let title="Magnet-раздача";try{title=new URL(magnet).searchParams.get("dn")?.trim()||title}catch{title="Magnet-раздача"}return {title,size:"—",seeders:0,peers:0,magnet,hash:"",tracker:"Magnet",year:null,quality:"Magnet"}}

export default function Home(){
  const [library,setLibrary]=useState(EMPTY);const [screen,setScreen]=useState("overview");const [query,setQuery]=useState("");const [search,setSearch]=useState<SearchPayload>({query:"",metadata:null,results:[]});const [busy,setBusy]=useState(false);const [quality,setQuality]=useState("Все");const [toast,setToast]=useState("");const [selectedTorrent,setSelectedTorrent]=useState<Media|null>(null);const [torrentFiles,setTorrentFiles]=useState<TorrentFile[]>([]);const [filesBusy,setFilesBusy]=useState(false);const [filesError,setFilesError]=useState("");
  const [syncBusy,setSyncBusy]=useState(false);const [preferences,setPreferences]=useState<Preferences|null>(null);const addLock=useRef(false);const filesRequest=useRef(0);
  const en=preferences?.language==="en";const nav=[{id:"overview",label:en?"Home":"Главная",icon:House},{id:"search",label:en?"Search":"Найти",icon:MagnifyingGlass},{id:"library",label:en?"Library":"Библиотека",icon:Books}];
  const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2600)};
  const loadLibrary=async(sync=false,full=false)=>{try{const response=await fetch(API+"/api/"+(sync?"sync":"library"),{method:sync?"POST":"GET",headers:sync?{"content-type":"application/json"}:undefined,body:sync?JSON.stringify({full}):undefined,cache:"no-store"});if(!response.ok)throw new Error();const payload=await response.json() as LibraryPayload;setLibrary(payload);return payload}catch{setLibrary(old=>({...old,state:{...old.state,online:false,syncing:false,error:"Локальный API не запущен"}}));return null}};
  const runSearch=async(value=query)=>{const clean=value.trim();if(clean.length<2)return;setSelectedTorrent(null);setScreen("search");if(isMagnetInput(clean)){const release=releaseFromMagnet(clean);setSearch({query:release.title,metadata:{title:release.title,year:null},results:[release]});setQuality("Все");await add(release,true);return}setBusy(true);try{const response=await fetch(`${API}/api/search?q=${encodeURIComponent(clean)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setSearch({...payload,metadata:payload.metadata??{title:clean,year:null}});setQuality("Все")}catch(error){const message=error instanceof Error?error.message:"";notify(/fetch failed|not running/i.test(message)?"TorrServer недоступен":message||"Поиск недоступен")}finally{setBusy(false)}};
  useEffect(()=>{const timer=window.setTimeout(()=>{void loadLibrary().then(()=>loadLibrary(true))},0);return()=>window.clearTimeout(timer)},[]);
  useEffect(()=>{void fetch(API+"/api/settings",{cache:"no-store"}).then(response=>response.json()).then(setPreferences)},[]);
  useEffect(()=>{if(preferences)document.documentElement.lang=preferences.language},[preferences]);
  const savePreferences=async(next:Preferences)=>{const response=await fetch(API+"/api/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(next)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setPreferences(payload)};
  useEffect(()=>{if(!syncBusy&&!library.state.syncing)return;const timer=window.setInterval(()=>void loadLibrary(),1500);return()=>window.clearInterval(timer)},[syncBusy,library.state.syncing]);
  const qualities=useMemo(()=>["Все",...Array.from(new Set(search.results.map(item=>item.quality)))],[search.results]);
  const releases=useMemo(()=>quality==="Все"?search.results:search.results.filter(item=>item.quality===quality),[quality,search.results]);
  const details=search.metadata;const poster=imageSrc(details?.posterUrl);const gallery=details?.gallery??[];
  const add=async(release:Release,playNow=false)=>{
    if(addLock.current)return;
    addLock.current=true;setBusy(true);
    try{
      const response=await fetch(API+"/api/torrents/add",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({magnet:release.magnet,title:release.title})});
      const payload=await response.json();if(!response.ok)throw new Error(payload.error);
      notify(payload.alreadyExists?"Раздача уже сохранена в TorrServer":"Раздача добавлена в TorrServer");
      await loadLibrary();
      if(playNow&&payload.item)await openTorrent(payload.item);
    }catch(error){notify(error instanceof Error?error.message:"Не удалось добавить раздачу")}
    finally{addLock.current=false;setBusy(false)}
  };
  const loadTorrentFiles=async(item:Media)=>{const response=await fetch(`${API}/api/torrents/${encodeURIComponent(item.torrentHash)}/files`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error);return (payload.files??[]) as TorrentFile[]};
  const openTorrent=async(item:Media)=>{
    const requestId=++filesRequest.current;
    setSelectedTorrent(item);setTorrentFiles([]);setFilesError("");setFilesBusy(true);
    try{const files=await loadTorrentFiles(item);if(requestId===filesRequest.current)setTorrentFiles(files)}
    catch(error){if(requestId===filesRequest.current)setFilesError(error instanceof Error?error.message:"Не удалось получить список видеофайлов")}
    finally{if(requestId===filesRequest.current)setFilesBusy(false)}
  };
  const removeMedia=async(item:Media)=>{if(!window.confirm(`Удалить «${item.title}» из медиатеки и TorrServer?`))return;try{const response=await fetch(`${API}/api/torrents/${encodeURIComponent(item.torrentHash)}`,{method:"DELETE"});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setLibrary(current=>({...current,items:current.items.filter(media=>media.torrentHash!==item.torrentHash),continueWatching:current.continueWatching.filter(media=>media.torrentHash!==item.torrentHash),recentlyAdded:current.recentlyAdded.filter(media=>media.torrentHash!==item.torrentHash),stats:{...current.stats,total:Math.max(0,current.stats.total-1),active:Math.max(0,current.stats.active-(item.isActive?1:0))}}));notify(`«${item.title}» удалён из TorrServer`)}catch(error){notify(error instanceof Error?error.message:"Не удалось удалить раздачу")}};
  const syncNow=async()=>{
    if(syncBusy)return;
    setSyncBusy(true);
    try{const payload=await loadLibrary(true,true);notify(!payload||payload.state.error?payload?.state.error??"Не удалось синхронизировать медиатеку":"Синхронизация завершена: "+payload.stats.total+" раздач")}
    finally{setSyncBusy(false)}
  };
  return <main className="pirate-cinema-app">
    <aside className="nav-rail"><div className="brand-block"><button className="logo" onClick={()=>{setSelectedTorrent(null);setScreen("overview")}}>Pirate Cinema</button><img className="brand-logo" src="/pirate-cinema-logo.png" alt="Pirate Cinema"/></div><nav>{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={screen===item.id?"selected":""} onClick={()=>{setSelectedTorrent(null);setScreen(item.id)}}><Icon size={23}/><span>{item.label}</span></button>})}</nav><div className="rail-bottom"><button className={screen==="settings"?"selected":""} onClick={()=>{setSelectedTorrent(null);setScreen("settings")}}><GearSix size={23}/><span>{en?"Settings":"Настройки"}</span></button></div></aside>
    <section className="workspace">
      <header className="search-header"><form onSubmit={event=>{event.preventDefault();runSearch()}}><MagnifyingGlass size={24}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={en?"Find a movie, series, or paste a magnet link":"Найти фильм, сериал или вставить magnet-ссылку"}/><button type="submit" aria-label={en?"Search":"Найти"}>{busy?<CircleNotch className="spin" size={20}/>:<span>{en?"Search":"Найти"}</span>}</button></form><button className="server-pill" onClick={()=>loadLibrary(true)}><i className={library.state.online?"":"offline"}/><span>{library.state.online?`TorrServer · ${library.state.serverVersion??(en?"online":"онлайн")}`:`TorrServer ${en?"offline":"офлайн"}`}</span></button></header>
      {!selectedTorrent&&screen==="search"&&<div className="search-view">
        <section className="feature">{details?<><div className="feature-main">{poster?<img className="feature-poster" src={poster} alt=""/>:<div className="feature-poster poster-empty"><FilmStrip size={48}/></div>}<div className="feature-copy"><p className="kicker">{[details.year,seconds(details.runtimeSeconds),details.rating?`★ ${details.rating}`:null].filter(Boolean).join(" · ")}</p><h1>{details.title}</h1><p className="genres">{details.genres?.join(" · ")||"Фильм или сериал"}</p><p className="overview">{details.overview||"Выберите подходящую раздачу справа."}</p><WikipediaCredit url={details.overviewSourceUrl}/><dl><div><dt>ИСТОЧНИК</dt><dd>{details.provider==="tmdb"?"TMDB":"Поиск TorrServer"}</dd></div><div><dt>ХРАНЕНИЕ</dt><dd>SQLite</dd></div></dl></div></div>{gallery.length>0&&<div className="gallery">{gallery.slice(0,2).map((src,index)=><img key={src} src={src} alt={index?"Кадр 2":"Кадр 1"}/>)}</div>}<div className="feature-actions"><button className="secondary-action" disabled={!releases[0]||busy} onClick={()=>releases[0]&&add(releases[0])}><Plus size={20}/>Добавить в TorrServer</button><button className="primary-action" disabled={!releases[0]||busy} onClick={()=>releases[0]&&add(releases[0],true)}><Play weight="fill" size={18}/>Смотреть сейчас</button></div></>:<div className="search-empty-feature"><MagnifyingGlass size={38}/><h1>Начните с поиска</h1><p>Введите название фильма или сериала — здесь появятся описание и доступные раздачи.</p></div>}</section>
        <section className="release-panel"><div className="release-title"><div><span>РЕЗУЛЬТАТЫ ПОИСКА</span><h2>Раздачи</h2></div><button title="Вставить magnet-ссылку" onClick={()=>{const value=window.prompt("Вставьте magnet-ссылку");if(value){const release=releaseFromMagnet(value);setSearch({query:release.title,metadata:{title:release.title,year:null},results:[release]});void add(release,true)}}}><Magnet size={22}/></button></div><div className="quality-tabs">{qualities.map(item=><button key={item} className={quality===item?"active":""} onClick={()=>setQuality(item)}>{item}</button>)}</div><div className="columns"><span>Название</span><span>Размер</span><span>Сиды</span><span/></div><div className="release-list">{busy&&!search.results.length?<div className="release-empty"><CircleNotch className="spin" size={26}/><span>Ищем раздачи…</span></div>:releases.length?releases.slice(0,14).map((item,index)=><article key={`${item.hash}-${index}`} className={index===0?"best":""}><button className="release-info" disabled={busy} onClick={()=>add(item,true)}><span className="release-name"><b>{item.quality}</b>{item.title}</span><span>{item.size}</span><strong>{item.seeders.toLocaleString("ru-RU")}</strong><i><Play weight="fill" size={15}/></i></button><button className="release-add" disabled={busy} onClick={()=>void add(item,false)} aria-label={"Добавить в TorrServer: "+item.title}><Plus size={16}/>Добавить в TorrServer</button></article>):<div className="release-empty"><Magnet size={28}/><span>Введите название фильма, сериала или magnet-ссылку</span></div>}</div></section>
      </div>}
      {!selectedTorrent&&screen==="overview"&&<Overview language={preferences?.language??"ru"} onSelect={movie=>{const value=`${movie.originalTitle} ${movie.year}`;setQuery(value);void runSearch(value)}} />}
      {!selectedTorrent&&screen==="library"&&<LibraryView title={en?"Library":"Медиатека"} subtitle={en?"Select a card, then choose the exact movie or episode to play":"Выберите карточку, затем укажите конкретный фильм или серию для запуска"} items={library.items} onSelect={openTorrent} onDelete={removeMedia} />}
      {!selectedTorrent&&screen==="settings"&&<Settings state={library.state} count={library.stats.total} busy={syncBusy} onSync={syncNow} preferences={preferences} onSavePreferences={savePreferences} />}

      {selectedTorrent&&<MediaFilePicker key={selectedTorrent.torrentHash} item={selectedTorrent} files={torrentFiles} busy={filesBusy} error={filesError} onClose={()=>setSelectedTorrent(null)} onRetry={()=>openTorrent(selectedTorrent)} onRefresh={async()=>setTorrentFiles(await loadTorrentFiles(selectedTorrent))} onLaunched={notify}/>}
      <PlaybackBar/>
    </section>
    {toast&&<div className="toast"><Check size={18}/>{toast}</div>}
    {preferences&&!preferences.onboardingComplete&&<Welcome value={preferences} onSave={savePreferences}/>}
  </main>
}

function Overview({onSelect,language}:{onSelect:(movie:TopMovie)=>void;language:"ru"|"en"}){const en=language==="en";return <section className="simple-page top-page"><div className="top-heading"><div><span className="page-label">{en?"POPULAR NOW":"ПОПУЛЯРНО СЕЙЧАС"}</span><h1>{en?"Popular on Kinopoisk":"Популярное на Кинопоиске"}</h1><p>{en?"Top 20 movies and series — select a card to find a torrent.":"Первые 20 фильмов и сериалов — выберите карточку, чтобы найти раздачу."}</p></div><span className="top-mark">TOP</span></div><div className="top-grid">{TOP_MOVIES.map(movie=><article key={movie.imdbId}><button onClick={()=>onSelect(movie)}><div className="top-poster"><img src={movie.posterUrl??`https://images.metahub.space/poster/medium/${movie.imdbId}/img`} alt=""/><b>#{movie.rank}</b><span>★ {movie.rating.toFixed(1)}</span></div><strong>{en?movie.originalTitle:movie.title}</strong><small>{movie.originalTitle} · {movie.year}</small></button></article>)}</div></section>}
function LibraryView({title,subtitle,items,onSelect,onDelete}:{title:string;subtitle:string;items:Media[];onSelect?:(item:Media)=>void;onDelete?:(item:Media)=>void}){return <section className="simple-page library-page"><span className="page-label">PIRATE CINEMA</span><h1>{title}</h1><p>{subtitle}</p>{items.length?<div className="media-grid">{items.map(item=><article key={`${item.torrentHash}-${item.posterPath??item.posterUrl??"frame"}`}><button className="media-card" onClick={()=>onSelect?.(item)}><div><PosterImage item={item}/>{item.progress!==null&&<i style={{width:`${item.progress}%`}}/>}</div><strong>{item.title}</strong><span>{item.year??"Без года"}</span></button><button className="media-delete" title="Удалить из медиатеки и TorrServer" aria-label={`Удалить ${item.title}`} onClick={()=>onDelete?.(item)}><Trash size={18}/></button></article>)}</div>:<div className="page-empty"><Database size={34}/><strong>Здесь пока пусто</strong><span>Добавьте раздачу через поиск.</span></div>}</section>}
function PosterImage({item}:{item:Media}){const fallback=`${API}/api/posters/frame/${item.torrentHash}`;const preferred=imageSrc(item.posterPath??item.posterUrl);const initial=preferred&&!/no-poster/i.test(preferred)?preferred:fallback;const [src,setSrc]=useState(initial);const [failed,setFailed]=useState(false);if(failed)return <span className="poster-placeholder"><FilmStrip size={34}/></span>;return <img src={src} alt="" onError={()=>{if(src!==fallback)setSrc(fallback);else setFailed(true)}}/>}
function Settings({state,count,busy,onSync,preferences,onSavePreferences}:{state:AppState;count:number;busy:boolean;onSync:()=>void;preferences:Preferences|null;onSavePreferences:(next:Preferences)=>Promise<void>}){
  const en=preferences?.language==="en";const metadataTitle=state.metadataMode==="tmdb"?"TMDB":state.metadataMode==="open"?"Cinemeta + TVmaze + Wikipedia":en?"Posters from TorrServer":"Постеры из TorrServer";const metadataHint=state.metadataMode==="tmdb"?"TMDB Read Access Token":state.metadataMode==="open"?(en?"Remote poster search enabled":"Удалённый поиск постеров включён"):(en?"Remote search disabled for privacy":"Удалённый поиск выключен для приватности");
  return <section className="simple-page settings-page"><span className="page-label">{en?"LOCAL CONFIGURATION":"ЛОКАЛЬНАЯ КОНФИГУРАЦИЯ"}</span><h1>{en?"Settings":"Настройки"}</h1><p className="app-version">Pirate Cinema · {en?"Version":"Версия"} {appVersion}</p><p>{en?"Your library and search cache stay on this computer.":"Медиатека и кэш поиска хранятся на этом компьютере."}</p>{preferences&&<PlayerPreferences value={preferences} onSave={onSavePreferences}/>}<div className="settings-list"><article><HardDrives size={25}/><div><span>TorrServer</span><strong>{state.torrServerUrl}</strong><small>{state.online?`${en?"Connected":"Подключён"} · ${state.serverVersion}`:(en?"No connection":"Нет соединения")}</small></div></article><article><Magnet size={25}/><div><span>{en?"Torrent search":"Поиск раздач"}</span><strong>{state.searchProviders?.join(" · ")||"TorrServer + Rutor"}</strong><small>{en?"The built-in TorrServer is the only search source":"Единственный источник поиска — встроенный TorrServer"}</small></div></article><article><Pulse size={25}/><div><span>{en?"Posters and metadata":"Постеры и метаданные"}</span><strong>{metadataTitle}</strong><small>{metadataHint}</small></div></article><article><SlidersHorizontal size={25}/><div><span>{en?"Local database":"Локальная база"}</span><strong>SQLite · media.db</strong><small>{count} {en?"saved items":"сохранённых позиций"}</small></div></article></div><button className="primary-action sync-now" disabled={busy||state.syncing} onClick={onSync}><Pulse size={19}/>{busy||state.syncing?(en?"Syncing…":"Синхронизируем…"):(en?"Sync entire library":"Синхронизировать всю медиатеку")}</button>{state.syncProgress&&<p role="status">{en?`Processed ${state.syncProgress.processed} of ${state.syncProgress.total} · failed: ${state.syncProgress.failed}`:`Обработано ${state.syncProgress.processed} из ${state.syncProgress.total} · не удалось обновить: ${state.syncProgress.failed}`}</p>}{state.error&&<p role="alert">{state.error}</p>}</section>
}
