const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const sandbox = {window:{}};
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../assets/player-state.js'),'utf8'),sandbox);
const state = sandbox.window.PiratePlayerState;
assert.equal(state.canStart(false, false), false);
assert.equal(state.canStart(true, true), false);
assert.equal(state.canStart(true, false), true);
assert.equal(state.startupReady(10,0,10),true);
assert.equal(state.startupReady(100,95,5),true);
assert.equal(state.startupReady(100,100,5),false);
assert.equal(state.startupReady(100,0,10),false);
const tracks = [{ Index: 7, Language: 'rus', Title: 'Studio A' }, { Index: 0, Language: 'eng', Title: 'Original' }];
assert.equal(state.preferredTrack(tracks, { language: 'rus', title: 'Studio A', index: 0 }), 0);
assert.equal(state.preferredTrack(tracks, { language: 'eng', title: 'Changed' }), 1);
assert.equal(state.preferredTrack(tracks, { language: 'jpn', title: 'Missing' }), -1);
assert.equal(state.shouldPrepare(100, 31, true, false), true);
assert.equal(state.shouldPrepare(100, 12, true, false), false);
assert.equal(state.shouldPrepare(100, 31, false, false), false);
assert.equal(state.shouldPrepare(100, 31, true, true), false);
assert.match(state.subtitleVtt('1\r\n00:00:01,000 --> 00:00:02,500\r\nТекст'), /WEBVTT\n\n1\n00:00:01.000 --> 00:00:02.500/);
console.log('Visibility, stable audio identity, bounded preparation and subtitles: OK');
